version: '2.1'
services:
    dhaskell:
        build:
            context: ./8.6/
            dockerfile: Dockerfile
        image: huangyingw/dhaskell
        volumes:
            - ./var/logs/:/var/logs/
            - ~/loadrc/:/root/loadrc/
            - ~/.ssh/:/root/.ssh/
            - ~/loadrc/gitrc/.gitconfig:/root/.gitconfig
            - ./:/code
        command: /bin/sh -c "/entrypoint.sh 2>&1 | tee /var/logs/containner.log"
